name: cppcheck-action-test

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64
        
      - name: Build with g++
        run: g++ -o main main.cpp
        
      - uses: actions/upload-artifact@v2
        name: Upload Artifact
        with:
          name: Main
          path: main

